FROM scratch
ADD . /
CMD ["/bin/bash"]

ARG created=unknown
ARG revision=unknown
LABEL org.opencontainers.image.vendor="АО НППКТ"
LABEL org.opencontainers.image.authors="Лаборатория 50"
LABEL org.opencontainers.image.title="ОСнова Onyx"
LABEL org.opencontainers.image.version="3.0"
LABEL org.opencontainers.image.created=$created
LABEL org.opencontainers.image.url="https://rudev.io/prods/основа/"
LABEL org.opencontainers.image.documentation="https://github.com/laboratory50/vagrant-boxes/blob/main/README.md"
LABEL org.opencontainers.image.source="https://github.com/laboratory50/vagrant-boxes"
LABEL org.opencontainers.image.revision=$revision
