FROM scratch
ADD . /
CMD ["/bin/bash"]

ARG created=unknown
LABEL org.opencontainers.image.vendor="АО НППКТ"
LABEL org.opencontainers.image.authors="Лаборатория 50"
LABEL org.opencontainers.image.title="ОСнова Onyx"
LABEL org.opencontainers.image.version="3.0"
LABEL org.opencontainers.image.created=$created
