FROM scratch
ADD . /
CMD ["/bin/bash"]

ARG version=unknown
ARG created=unknown
ARG revision=unknown
LABEL org.opencontainers.image.vendor="НЦПР"
LABEL org.opencontainers.image.authors="Лаборатория 50"
LABEL org.opencontainers.image.title="МСВСфера"
LABEL org.opencontainers.image.version=$version
LABEL org.opencontainers.image.created=$created
LABEL org.opencontainers.image.url="https://rudev.io/prods/мсвсфера/"
LABEL org.opencontainers.image.description="МСВСфера АРМ с systemd базовый образ"
LABEL org.opencontainers.image.source="https://github.com/laboratory50/vagrant-boxes"
LABEL org.opencontainers.image.revision=$revision
