FROM scratch
ADD . /
CMD ["/bin/bash"]

ARG version=unknown
ARG created=unknown
ARG revision=unknown
LABEL org.opencontainers.image.vendor="АО НТЦ ИТ РОСА"
LABEL org.opencontainers.image.authors="Лаборатория 50"
LABEL org.opencontainers.image.title="РОСА Фреш"
LABEL org.opencontainers.image.version=$version
LABEL org.opencontainers.image.created=$created
LABEL org.opencontainers.image.url="https://rudev.io/prods/роса/"
LABEL org.opencontainers.image.documentation="https://github.com/laboratory50/vagrant-boxes/blob/main/README.md"
LABEL org.opencontainers.image.description="РОСА Фреш с поддержкой systemd"
LABEL org.opencontainers.image.source="https://github.com/laboratory50/vagrant-boxes"
LABEL org.opencontainers.image.revision=$revision
