FROM scratch
ADD . /
CMD ["/bin/bash"]

ARG created=unknown
LABEL org.opencontainers.image.vendor="АО НТЦ ИТ РОСА"
LABEL org.opencontainers.image.authors="Лаборатория 50"
LABEL org.opencontainers.image.title="РОСА ФРЕШ"
LABEL org.opencontainers.image.version="12.5.1"
LABEL org.opencontainers.image.created=$created
